### ISSUE TITLE
DishCell 업데이트

### ISSUE THREAD

**Issue by 1song2** [rla36/sidedish#14]
- [x] Image download를 Asynchronously하게 처리
- [x] 메뉴 설명은 한 줄이며 wrap으로 설정하여 길이가 길면 ...으로 표현
- [x] 셀 크기 조정
- [x] originalPrice에 strikethrough 효과 주기
- [x] UIcollectoinView section에 edge inset 주기
- [x] badge가 없거나 하나 이상인 경우 처리
- [x] nameLabel의 trailing constraint 처리해주기

**Comment by JacksonPk** [comment]
badge가 없거나 하나 이상인 경우 처리
 - 의견 : 뱃지 방식으로 두개를 설정해서 카운트를 재서 카운트만큼보여주는방식?

**Comment by 1song2** [comment]
> badge가 없거나 하나 이상인 경우 처리
> 
> * 의견 : 뱃지 방식으로 두개를 설정해서 카운트를 재서 카운트만큼보여주는방식?

구현하기 간단하고 깔끔한 방법인 것 같아요! 대신 최대 badge 수가 늘어난다든지 변화가 있을 때 유연하게 대처하긴 어려울 것 같은 우려가🤔
같이 좀 더 생각해봅시다!
